name: Deploy Flutter Web

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: stable

      - run: flutter pub get
      - run: flutter build web --release --base-href /flutter_portfolio/ --dart-define=FLUTTER_WEB_CANVASKIT_URL=/canvaskit/

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          enable_jekyll: false
          keep_files: false
